---
- name: Configure DNS for the Ansible Tower node
  become: false
  community.aws.route53:
    state: "{{ s3_state }}"
    zone: "{{workshop_dns_zone}}"
    record: "{{username}}.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
    type: A
    overwrite: true
    value: "{{ansible_host}}"
  delegate_to: localhost
