---
- name: determine if Automation controller
  stat:
    path: /etc/sysconfig/automation-controller
  register: controller_path

- name: controller or tower
  set_fact:
    controller_or_tower: "{{ 'controller' if controller_path.stat.exists else 'tower' }}"

- name: SSL cert block
  block:
    - name: controller/tower start
      include_tasks: "service/{{ controller_or_tower }}_start.yml"

    # directions found here https://certbot.eff.org/lets-encrypt/centosrhel8-other
    - name: install certbot if not already installed
      dnf:
        name: certbot
        state: present
        disable_gpg_check: true
    # solves error
    # pkg_resources.DistributionNotFound: The 'requests>=2.14.2' distribution was not found and is required by acme
    - name: Install requests python package
      pip:
        name: requests>=2.14.2

    - name: Install requests python package
      pip:
        name: requests>=2.14.2

    - &tower-pinger-block
      block:
        - name: check Tower status
          shell: "curl --user 'admin:{{ admin_password }}' -vkL -XGET https://localhost/api/v2/ping/"
          register: check2
        - name: Display /api/v2/ping results (stdout)
          debug:
            msg: '{{ check2.stdout }}'
        - name: Display /api/v2/ping results (stderr)
          debug:
            msg: '{{ check2.stderr }}'

    - name: change ansible tower base URL
      block:
        - &tower-baseurl-task
          awx.awx.tower_settings:
            name: TOWER_URL_BASE
            value: "https://{{ dns_name }}"
            tower_verify_ssl: false
            tower_host: https://localhost/
            tower_username: admin
            tower_password: "{{ admin_password }}"
          register: change_base_url
          until: change_base_url is not failed
          # tower may not be fully up yet, wait for it gratuitously
          retries: 12
          delay: 5
      rescue:
        - name: controller/tower restart
          include_tasks: "service/{{ controller_or_tower }}_restart.yml"

        - *tower-pinger-block

        - <<: *tower-baseurl-task
          name: Run failed task again

    - name: controller/tower stop
      include_tasks: "service/{{ controller_or_tower }}_stop.yml"

    - name: Move SSL Key
      copy:
        remote_src: true
        src: "/etc/letsencrypt/live/{{ dns_name }}/privkey.pem"
        dest: /etc/tower/tower.key

    - name: Retrieve Specific SSL Cert
      slurp:
        src: "/etc/letsencrypt/live/{{ dns_name }}/cert.pem"
      register: intermediate_cert

    - name: Combine Specific and intermediate Cert
      template:
        src: combined_cert.j2
        dest: /etc/tower/tower.cert
  rescue:
    - name: no SSL cert for Automation Controller
      debug:
        msg: "SSL cert problem - no cert applied"
  always:
    # Turn on Ansible Controller if successful
    - name: controller/tower restart
      include_tasks: "service/{{ controller_or_tower }}_start.yml"
