---
- name: print out connection vars to hosts
  debug:
    msg:
      - "ansible_host {{ ansible_host }}"
      - "ansible_user {{ ansible_user }}"
      - "ansible_ssh_private_key_file {{ ansible_ssh_private_key_file }}"
      - "groups {{ groups }}"

- name: Wait 400 seconds (using wait_for_connection)
  wait_for_connection:
    delay: 0
    timeout: 400
