---
- name: make sure .ssh is created
  file:
    path: "/home/{{username}}/.ssh/"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory

- name: Install ansible-navigator.yml in home directory
  template:
    src: ansible-navigator.yml.j2
    dest: "/home/{{ username }}/.ansible-navigator.yml"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Apply patch for runner fix PR759
  lineinfile:
    path: /usr/lib/python3.8/site-packages/ansible_runner/config/_base.py
    regexp: ".*--userns=keep-id.*"
    state: absent

##
# @todo @craig-br This needs immprovement. Multiple ssh-agent instances
# are running for each bash session
##
- name: add custom bashrc for student
  template:
    src: bashrc.j2
    dest: /home/{{ username }}/.bashrc
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

# Login into Red Hat registry
- name: Login to redhat registry
  containers.podman.podman_login:
    username: '{{ redhat_username }}'
    password: '{{ redhat_password }}'
    registry: '{{ ee_registry_name }}'
  become_user: "{{ username }}"
  register: login_registry
  until: login_registry is not failed
  retries: 5

# Pull specific EE for each workshop based on workshop name
- name: Pull execution environment for {{ workshop_type }} workshop
  become_user: "{{ username }}"
  containers.podman.podman_image:
    name: "{{ lookup('vars', workshop_type + '_ee') }}"
  register: podman_pull
  until: podman_pull is not failed
  retries: 5
# This may look redundant, but you can't put these in a loop because the
# ansible_user will not be templated the way you expect when running under
# Controller/AWX

- name: copy over ssh config file for student
  template:
    src: sshconfig.j2
    dest: /home/{{ username }}/.ssh/config
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0700

- name: Put ssh-key in proper spot for student
  copy:
    src: "{{ output_dir }}/{{ ec2_name_prefix }}-private.pem"
    dest: "/home/{{ username }}/.ssh/id_rsa"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0400
  when: workshop_type is defined
