---
- name: initial check setup
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  vars_files:
   - "{{ target_env }}/group_vars/all.yml"
   - "{{ target_env }}/group_vars/vpc_rules.yml"
  tasks:
    - name: workshop collection final check
      block:
        - name: run pre-check role to make sure workshop will complete provisioning
          include_role:
            name: ../roles/check_setup

        - name: run AWS check setup if using AWS
          include_role:
            name: ../roles/aws_check_setup

        - name: download AAP
          include_role:
            name: ../roles/aap_download
      rescue:
        - name: Error with setup
          fail:
            msg: The provisioner has failed during initial check_setup, please scroll up to see exact error.  

- name: Create lab instances in AWS
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars_files:
   - "{{ target_env }}/group_vars/all.yml"
   - "{{ target_env }}/group_vars/vpc_rules.yml"
  tasks:
    - name: Cluster nodes
      set_fact:
        control_nodes: 4
      when: create_cluster is defined and create_cluster|bool
    - include_role:
        name: ../roles/manage_ec2_instances

- name: wait for all nodes to have SSH reachability
  hosts: "managed_nodes:control_nodes:attendance"
  vars_files:
   - "{{ target_env }}/group_vars/all.yml"
   - "{{ target_env }}/group_vars/vpc_rules.yml"
  become: true
  gather_facts: false
  tasks:
    - include_role:
        name: ../roles/connectivity_test

- name: Configure common options on managed nodes and control nodes
  hosts: "managed_nodes:control_nodes"
  gather_facts: false
  become: true
  vars_files:
   - "{{ target_env }}/group_vars/all.yml"
   - "{{ target_env }}/group_vars/vpc_rules.yml"
  tasks:
    - include_role:
        name: ../roles/user_accounts
    - include_role:
        name: ../roles/common

- name: configure ansible control node
  hosts: '*ansible-1'
  gather_facts: true
  vars: 
    aap_archive: "{{ playbook_dir }}/{{ target_env }}/aap.tar.gz"
  vars_files:
   - "{{ target_env }}/group_vars/all.yml"
   - "{{ target_env }}/group_vars/vpc_rules.yml"
  become: true
  tasks:
    - include_role:
        name: ../roles/control_node

- name: configure private automation hub
  hosts: 'automation_hub'
  gather_facts: true
  become: true
  vars: 
    aap_archive: "{{ playbook_dir }}/{{ target_env }}/aap.tar.gz"
  vars_files:
   - "{{ target_env }}/group_vars/all.yml"
   - "{{ target_env }}/group_vars/vpc_rules.yml"
  tasks:
    - include_role:
        name: ../roles/private_automation_hub
      when:
        - automation_hub is defined
        - automation_hub|bool

- name: add dns entires for all student control nodes
  hosts: '*ansible-1'
  become: true
  gather_facts: false
  vars_files:
   - "{{ target_env }}/group_vars/all.yml"
   - "{{ target_env }}/group_vars/vpc_rules.yml"
  tasks:
    - include_role:
        name: ../roles/aws_dns
      when:
        - dns_type is defined
        - dns_type == "aws"
        - controllerinstall is defined
        - controllerinstall
  tags: control_node

- name: print out information for instructor
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
   - "{{ target_env }}/group_vars/all.yml"
   - "{{ target_env }}/group_vars/vpc_rules.yml"
  tasks:
    - name: set facts for output
      set_fact:
        summary_information: |
          PROVISIONER SUMMARY
          *******************
          - Workshop name is {{ec2_name_prefix}}
          - Private key is located at {{playbook_dir}}/{{ target_env }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem

          FAILURES
          *******************
          {{ dns_information}}
          {{callback_information}}
          {{ demo_information }}

    - name: Print Summary Information
      debug:
        msg: "{{ summary_information }}"
