---
# Make sure we can re-run the automation platform installer during a lab without killing code-server access
- name: update Ansible installer nginx configuration template to support code server
  blockinfile:
    block: "{{ lookup('template', 'nginx.conf') }}"
    dest: /tmp/aap_install/roles/nginx/templates/nginx.conf
    insertafter: "http {"

# Make the block inserted above conditional to only apply to ansible-1
- name: Add jinja conditional start
  lineinfile:
    path: /tmp/aap_install/roles/nginx/templates/nginx.conf
    insertafter: "http {"
    line: '{% raw %} {% if ansible_hostname == "ansible-1" %} {% endraw %}'

# Make the block inserted above conditional to only apply to ansible-1
- name: Add jinja conditional end
  lineinfile:
    path: /tmp/aap_install/roles/nginx/templates/nginx.conf
    insertbefore: "include(.*)/etc/nginx/mime.types;"
    line: '{% raw %} {% endif %} {% endraw %}'
